key: "${APP_KEY}"
name: "${ADMIN_APP_NAME}"
trace:
  endpoint: ""
server:
  http:
    addr: 0.0.0.0:8082
    timeout: 30s
data:
  database:
    driver: "mysql"
    dsn: "${EXAMPLE_DB_DSN}"

log:
  dir: "./logs/"
  level: "debug"
  maxAge: 30       # day
  rotationTime: 1  # day